# Generated by Django 6.1.1 on 2026-09-22 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contracts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('confirmed', 'تایید شده'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('stock_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج قطعی کالا از انبار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='سفارش فقط تحت یک قرارداد فعال قابل ثبت است.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contracts.contract', verbose_name='قرارداد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.company', verbose_name='شرکت (Tenant)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.warehouse', verbose_name='انبار مبدا')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='قیمت واحد (لحظه ثبت سفارش)')),
                ('currency', models.CharField(max_length=3, verbose_name='واحد ارز')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='نسخه محصول')),
            ],
            options={
                'verbose_name': 'ردیف سفارش',
                'verbose_name_plural': 'ردیف\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت سفارش',
                'verbose_name_plural': 'تاریخچه وضعیت سفارش\u200cها',
                'ordering': ['-changed_at'],
            },
        ),
    ]
