# Generated by Django 6.1.1 on 2026-09-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='مبلغ کل (ریال)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.company', verbose_name='شرکت (Tenant)')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت زیر\u200cسفارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order', verbose_name='سفارش اصلی')),
            ],
            options={
                'verbose_name': 'زیر\u200cسفارش',
                'verbose_name_plural': 'زیر\u200cسفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='قیمت واحد (ریال)')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='نسخه محصول')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.suborder', verbose_name='زیر\u200cسفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
