# Generated by Django 6.1.1 on 2026-09-13 06:27

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('role', models.CharField(blank=True, choices=[('super_admin', 'ادمین ارشد'), ('sales_manager', 'مدیر فروش'), ('sales_expert', 'کارشناس فروش'), ('finance', 'مالی'), ('warehouse', 'انباردار'), ('agent', 'نماینده'), ('observer', 'ناظر')], max_length=20, null=True, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, help_text='مستقل از Role بیزینسی — فقط دسترسی پنل ادمین جنگو.', verbose_name='دسترسی Django Admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='مرز Multi-tenancy؛ فقط برای Superuser پلتفرمی خالی می\u200cماند.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.company', verbose_name='شرکت (Tenant)')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
