# Generated by Django 6.1.1 on 2026-09-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار')], max_length=10, verbose_name='نوع')),
                ('amount_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='مبلغ (تومان)')),
                ('reference', models.CharField(help_text='شماره پیش\u200cفاکتور یا ارجاع پرداخت', max_length=100, verbose_name='مرجع')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'ردیف دفتر مالی',
                'verbose_name_plural': 'دفتر مالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
