# Generated by Django 6.1.1 on 2026-09-16 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام انبار')),
                ('code', models.CharField(max_length=30, verbose_name='کد انبار')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenants.company', verbose_name='شرکت (Tenant)')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'ورود کالا'), ('issue', 'خروج کالا'), ('reserve', 'رزرو'), ('release', 'آزادسازی رزرو'), ('adjustment', 'اصلاح دستی'), ('transfer_in', 'انتقال ورودی'), ('transfer_out', 'انتقال خروجی')], max_length=20, verbose_name='نوع تغییر')),
                ('quantity', models.IntegerField(help_text='مثبت برای افزایش موجودی فیزیکی، منفی برای کاهش.', verbose_name='تعداد')),
                ('on_hand_after', models.PositiveIntegerField(verbose_name='موجودی پس از تغییر')),
                ('reserved_after', models.PositiveIntegerField(verbose_name='رزرو پس از تغییر')),
                ('reference', models.CharField(blank=True, help_text='شماره سفارش، رسید انبار یا هر شناسه مرتبط.', max_length=100, verbose_name='مرجع')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'دفتر موجودی',
                'verbose_name_plural': 'دفتر موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.PositiveIntegerField(default=0, verbose_name='موجودی فیزیکی')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='رزرو شده')),
                ('reorder_point', models.PositiveIntegerField(default=0, verbose_name='نقطه سفارش مجدد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.productvariant', verbose_name='نسخه محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی انبارها',
                'ordering': ['warehouse__name', 'variant__sku'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='شماره سریال')),
                ('status', models.CharField(choices=[('in_stock', 'موجود در انبار'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده'), ('returned', 'مرجوعی'), ('defective', 'معیوب')], db_index=True, default='in_stock', max_length=20, verbose_name='وضعیت')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ورود به انبار')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.productvariant', verbose_name='نسخه محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'سریال دستگاه',
                'verbose_name_plural': 'سریال دستگاه\u200cها',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_warehouse_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('warehouse', 'variant'), name='uniq_inventory_warehouse_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='chk_reserved_not_exceeding_on_hand'),
        ),
        migrations.AddIndex(
            model_name='deviceserial',
            index=models.Index(fields=['variant', 'warehouse', 'status'], name='idx_serial_allocation'),
        ),
    ]
