# Generated by Django 6.1.1 on 2026-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=30, verbose_name='درگاه')),
                ('gateway_reference', models.CharField(max_length=100, verbose_name='ارجاع درگاه')),
                ('idempotency_key', models.CharField(max_length=100, unique=True, verbose_name='کلید Idempotency')),
                ('amount_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='مبلغ (تومان)')),
                ('redirect_url', models.URLField(blank=True, verbose_name='آدرس بازگشت')),
                ('status', models.CharField(choices=[('created', 'ایجادشده'), ('pending', 'در انتظار تایید'), ('succeeded', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغوشده')], db_index=True, default='created', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
