# Generated by Django 6.1.1 on 2026-09-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pricing.proformainvoice', verbose_name='پیش\u200cفاکتور'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('gateway', 'gateway_reference'), name='uniq_gateway_reference'),
        ),
    ]
