# Generated by Django 6.1.1 on 2026-09-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='ارز')),
                ('rate_date', models.DateField(verbose_name='تاریخ نرخ')),
                ('rate_to_irt', models.DecimalField(decimal_places=4, help_text='مثلاً اگر ۱ دلار = ۶۵,۰۰۰ تومان، این مقدار 65000.0000 است.', max_digits=20, verbose_name='نرخ به تومان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ\u200cهای ارز',
                'ordering': ['-rate_date'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'rate_date'), name='uniq_rate_per_currency_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='شماره پیش\u200cفاکتور')),
                ('tax_rate', models.DecimalField(decimal_places=4, help_text='مثلاً 0.1000 برای ۱۰٪', max_digits=5, verbose_name='نرخ مالیات')),
                ('subtotal_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='جمع قبل از مالیات (تومان)')),
                ('tax_amount_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='مبلغ مالیات (تومان)')),
                ('total_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='مبلغ نهایی (تومان)')),
                ('status', models.CharField(choices=[('issued', 'صادرشده'), ('expired', 'منقضی\u200cشده'), ('converted', 'تبدیل به فاکتور قطعی')], default='issued', max_length=20, verbose_name='وضعیت')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان صدور')),
                ('valid_until', models.DateTimeField(verbose_name='اعتبار تا')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoice', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پیش\u200cفاکتور',
                'verbose_name_plural': 'پیش\u200cفاکتورها',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح کالا (Snapshot نام در لحظه صدور)')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price_original', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='قیمت واحد (ارز اصلی)')),
                ('currency_original', models.CharField(max_length=3, verbose_name='ارز اصلی')),
                ('exchange_rate_applied', models.DecimalField(decimal_places=4, help_text='برای اقلام تومانی همیشه 1.0000 است.', max_digits=20, verbose_name='نرخ ارز اعمال\u200cشده')),
                ('unit_price_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='قیمت واحد (تومان)')),
                ('line_subtotal_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='جمع ردیف قبل از مالیات')),
                ('line_tax_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='مالیات ردیف')),
                ('line_total_irt', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='جمع نهایی ردیف')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.proformainvoice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'ردیف پیش\u200cفاکتور',
                'verbose_name_plural': 'ردیف\u200cهای پیش\u200cفاکتور',
            },
        ),
    ]
