# Generated by Django 6.1.1 on 2026-09-16 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام برند')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='شناسه یکتا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='شناسه یکتا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('code', models.CharField(max_length=50, verbose_name='کد محصول')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('warranty_months', models.PositiveSmallIntegerField(default=12, verbose_name='گارانتی (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.company', verbose_name='شرکت (Tenant)')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً «GPRS - مشکی» یا «WiFi - سفید»', max_length=150, verbose_name='عنوان نسخه')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=60, verbose_name='بارکد')),
                ('base_price', models.DecimalField(decimal_places=4, help_text='مقادیر پولی همیشه Decimal هستند — استفاده از Float ممنوع است.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پایه')),
                ('currency', models.CharField(choices=[('IRT', 'تومان'), ('USD', 'دلار')], default='IRT', max_length=3, verbose_name='واحد ارز')),
                ('requires_serial', models.BooleanField(default=True, help_text='برای دستگاه\u200cهای کارتخوان فعال است؛ برای لوازم جانبی معمولاً خیر.', verbose_name='نیازمند ثبت سریال')),
                ('min_order_quantity', models.PositiveIntegerField(default=1, verbose_name='حداقل تعداد سفارش')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, verbose_name='زمان آماده\u200cسازی (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نسخه محصول',
                'verbose_name_plural': 'نسخه\u200cهای محصول',
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_product_code_per_tenant'),
        ),
    ]
