# Generated by Django 6.1.1 on 2026-09-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='شماره قرارداد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('agent_name', models.CharField(max_length=255, verbose_name='شرکت نماینده')),
                ('device_cap', models.PositiveIntegerField(verbose_name='سقف دستگاه')),
                ('end_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی\u200cشده'), ('pending', 'در انتظار تایید')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(help_text='مرز Multi-tenancy؛ شرکت توزیع\u200cکننده\u200cای که این قرارداد متعلق به آن است.', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tenants.company', verbose_name='شرکت (Tenant)')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-created_at'],
            },
        ),
    ]
